version: '3.9'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn my_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    # container_name: blog-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # nginx:
  #   build: 
  #     context: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web


volumes:
  static_volume:
  postgres_data: