version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    environment:
      - SECRET_KEY=django-insecure-og8tcno(dfu-u=r2b_lp*nwxbqdqi5fs+zi0+@x9na&l&+10*3
      - DEBUG=1
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
      