version: '3.9'

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn my_blog.wsgi:application --bind 0.0.0.0:8000
    entrypoint: ["/home/app/web/entrypoint.prod.sh"]
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env
    # depends_on:
    #   - db

  # db:
  #   image: postgres:14.0-alpine
  #   container_name: blog-db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/ 
  #   env_file:
  #     - ./.env.prod.db

  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  static_volume: