version: '3.9'

services:
  web:
    build:
      context: .
      args:
        - DEV=true
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app
      - ./data/web:/vol/web
    env_file:
      - .env
    networks:
      - my-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - my-network

  db:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_DB=myblogsite
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=testpass123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  postgres-data:


networks:
  my-network:
